//Problem-1 use Random function math.random get single digit.
{
  let singleDigit = Math.floor(Math.random() * 10) % 10;
  console.log(
    "Single digit number generated by random function is : " + singleDigit
  );
}